Repository nyxx-discord/nyxx_commands, pull requests merged in 2023-03, with the labels that each got.

#105 Add documentation for compiling nyxx_commands
  README.md
  lib/src/mirror_utils/compiled.dart
Labels: documentation

#101 Move event handling to EventManager
  lib/nyxx_commands.dart
  lib/src/commands.dart
  lib/src/context/base.dart
  lib/src/context/context_manager.dart
  lib/src/context/modal_context.dart
  lib/src/errors.dart
  lib/src/event_manager.dart
  lib/src/mirror_utils/compiled.dart
  lib/src/util/mixins.dart
  lib/src/util/util.dart
  pubspec.yaml
  test/unit/event_manager.dart
Labels: enhancement

#108 Update other catch blocks to handle all errors
  lib/src/commands/message_command.dart
  lib/src/commands/user_command.dart
  lib/src/errors.dart
  lib/src/event_manager.dart
Labels: bug

#109 Release 5.0.0-dev.2
  CHANGELOG.md
  pubspec.yaml
Labels: bug, documentation, enhancement

#112 Avoid late where possible
  lib/src/util/mixins.dart
Labels: bug

#111 Don't use response future as lock in acknowledge
  lib/src/util/mixins.dart
Labels: bug

#113 Correct multi-page selections not reusing the same message if preserveComponentMessages was set
  lib/src/context/base.dart
  lib/src/util/mixins.dart
Labels: bug

#114 chore: deps update
  CHANGELOG.md
  bin/compile/element_tree_visitor.dart
  bin/compile/function_metadata/metadata_builder.dart
  bin/compile/to_source.dart
  bin/compile/type_tree/tree_builder.dart
  lib/src/commands/chat_command.dart
  pubspec.yaml
Labels: documentation

#117 Release 5.0.0-dev.3
  CHANGELOG.md
  pubspec.yaml
Labels: bug

#116 fix: private files included in analysis
  CHANGELOG.md
  bin/compile/element_tree_visitor.dart
  pubspec.yaml
Labels: bug

#119 Add support for nyxx 5.0.0 and nyxx_interactions 4.6.0
  lib/src/context/context_manager.dart
  pubspec.yaml
Labels: enhancement

#120 Correct error message showing duplicate RuntimeTypes
  lib/src/commands.dart
Labels: bug

#122 Specify how to obtain a custom id from a ComponentId
  lib/src/util/util.dart
Labels: documentation
